import React, { Component } from 'react';
import { Row, Col} from 'reactstrap';
import Dish from './dish.js';

class Dishes extends Component {

  render() {

    let dishesItems;
    dishesItems = this.props.dishes.map( (dishItem, i) => {

      return (
        <Col>
          <Dish
            //pass individual dishItems to each Dish
            dishItem={dishItem}

            // elements generated by iteration should have an unique Key property
            key={i}

            //pass addToCart to Dish 
            addToCart={this.props.addToCart}
          />
        </Col>
      );
    })

    return (
      <Row>
        {dishesItems}
      </Row>
    );
  }
}

export default Dishes;
